import moment from 'moment';
import { QTableProps } from 'quasar';

export const columnasAuditoria: QTableProps['columns'] = [
  {
    name: 'doc_codigo',
    align: 'left',
    label: 'ID',
    field: 'doc_codigo',
  },
  {
    name: 'doc_acro',
    align: 'left',
    label: 'Tipo',
    field: 'doc_acro',
  },
  {
    name: 'compro',
    label: 'Comprobante',
    align: 'left',
    field: 'compro',
    sortable: true,
  },
  {
    name: 'comadc',
    align: 'left',
    label: 'comadc',
    field: 'comadc',
    sortable: true,
  },
  {
    name: 'fecreg',
    align: 'left',
    label: 'Fecha Transacción',
    field: 'fecreg',
    format: (val: string) => moment(val).format('DD-MM-YYYY HH:mm'),
    sortable: true,
  },
  {
    name: 'clpid',
    align: 'left',
    label: 'ID',
    field: 'clpid',
    sortable: true,
  },
  {
    name: 'clpdescri',
    align: 'left',
    label: 'RUC',
    field: 'clpdescri',
    sortable: true,
  },
  {
    name: 'clp_descri',
    align: 'left',
    label: 'Realizado por',
    field: 'clp_descri',
    sortable: true,
  },
  {
    name: 'numitems',
    align: 'center',
    label: '# Items',
    field: 'numitems',
    sortable: true,
  },
  {
    name: 'monto',
    align: 'left',
    label: 'Monto',
    field: 'monto',
    sortable: true,
  },
  {
    name: 'fecha',
    align: 'left',
    label: 'Registro',
    field: 'fecha',
    format: (val: string) => moment(val).format('DD-MM-YYYY HH:mm'),
    sortable: true,
  },
  {
    name: 'concepto',
    align: 'left',
    label: 'Motivo',
    field: 'concepto',
    sortable: true,
  },
  {
    name: 'login',
    align: 'left',
    label: 'Usuario',
    field: 'login',
    sortable: true,
  },
  {
    name: 'fpago',
    align: 'left',
    label: 'Forma de pago',
    field: 'fpago',
    sortable: true,
  },
  {
    name: 'detalle',
    align: 'left',
    label: 'Detalle',
    field: 'detalle',
    sortable: true,
  },
  {
    name: 'identicador',
    align: 'left',
    label: 'Identicador',
    field: 'identicador',
    sortable: true,
  },
];

export const columnasDetalles: QTableProps['columns'] = [
  {
    name: 'codigo',
    label: 'Cod. Barras',
    align: 'left',
    field: 'codigo',
  },
  {
    name: 'descripcion',
    label: 'Descripción',
    align: 'left',
    field: 'descripcion',
  },
  {
    name: 'cantidad',
    label: 'Cantidad',
    align: 'right',
    field: 'cantidad',
    format: (val) => val.toFixed(2),
  },
  {
    name: 'subtotal',
    label: 'Subtotal',
    align: 'right',
    field: 'subtotal',
    format: (val) => val.toFixed(2),
  },
];
